version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: development
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
