version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "05:00"
    allow:
      - dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:00"
